### ISSUE TITLE
psr-0-final-proposal not found

### ISSUE THREAD

**Issue by rikysunandi** [stephenmelrose/google-apis-php-clients#3]
http://groups.google.com/group/php-standards/web/psr-0-final-proposal link is broken.

**Comment by stephenmelrose** [comment]
Hi @rikysunandi. It is indeed, Google Code is no more. You can find the correct link here: http://www.php-fig.org/psr/psr-0/

I won't be updating this repo though as I don't actively work on this anymore I'm afraid. I think it's been 3 years since I last touched it. If you want to fork and continue development, be my guest.

**Comment by rikysunandi** [comment]
Ok Stephen, thank you. I will try to learn first.. :)

**Comment by rikysunandi** [comment]
Hi Stephen, why i still get 500 response? any suggest?
